#ifndef ERRORS_H
#define ERRORS_H

#include "global.h"

typedef enum{
	IF_ERR,ELSE_ERR,WHILE_ERR,REPEAT_ERR,FOR_ERR,WRITE_ERR,CAT_ERR,MIN_ERR,MAX_ERR,IN_ERR,BREAK_ERR,IS_ERR,AS_ERR,
	CLS_ERR,PV_ERR,PT_ERR,PLUS_ERR,
	MOINS_ERR,MULT_ERR,DIV_ERR,VIR_ERR,AFF_ERR,
	INF_ERR,INFG_ERR,SUP_ERR,SUPG_ERR,EGAL_ERR,DIFF_ERR,
	PO_ERR,PF_ERR,ID_ERR,NUM_ERR,ERREUR_ERR,COMM_ERR,AND_ERR,OR_ERR,NOT_ERR,RES_ERR,DIVENT_ERR,POW_ERR,ACCO_ERR,ACCF_ERR,SEQ_ERR,ENTRER_ERR,READ_ERR,CHAINE_ERR,EOF_ERR

}CODE_ERR;

void ERREUR(CODE_ERR error);
void compatibiliteError();

#endif
